### PR TITLE
Support to search property resources in multiple locations

### PR DESCRIPTION
**Pull request by basdewitte**
>  List<String> configLocations = Arrays.asList( "classpath:META-INF/conf/", "${MYAPP_HOME}/conf/");
> PropertyHolder holder = new PropertyHolder();
> PropertyValueInjector.inject(holder, configLocations);

@carlspring, if you think we are done for now so do I

### CODE REVIEW

**Comment by carlspring** [comment]
Thanks a lot for your contribution! :)
Is there anything else you would like to add? When would you like me to cut a release?

**Comment by basdewitte** [comment]
Thanks for taking care of the review so quickly.

I believe now would be a good time to cut a release. So if you agree, go 
ahead!

**Comment by carlspring** [comment]
I will look into it as soon as I have a chance by the end of the week.

**Comment by carlspring** [comment]
Hi Bas,

I have pushed a new release to Maven Central. It will take a few hours
before it gets updated and visible on Maven Central.

I've edited the README so that it now has a badge. Once the badge switched
to 1.8, you'll be able to used your latest changes!

Thanks for your help!
Kind regards,

Martin

**Comment by basdewitte** [comment]
Coool

**Pull request merged**
